# modules/locale.conf
---
region:    "Asia"
zone:      "Dhaka"
localeGenPath: "/etc/locale.gen"

# Default system locale written to /etc/locale.conf
locale: "en_US.UTF-8"

# Additional locales to generate
geoipUrl: "https://geoip.kde.org/v1/calamares"
geoipStyle: "json"
