# modules/packages.conf
# Packages to install or remove during installation.
---
backend: pacman

# Operations run after unpackfs
operations:
  - install:
      - networkmanager
      - grub
      - efibootmgr
      - os-prober
  - remove:
      - calamares             # Remove installer from final system
      - progos-calamares

# pacman-specific options
pacman:
  num_retries:   5
  disable_timeout: true
