# modules/partition.conf
---
efiSystemPartition:     "/boot/efi"
efiSystemPartitionSize: "300M"
efiSystemPartitionName: "EFI"

# Default filesystem for new partitions
defaultFileSystemType:  "ext4"

# Show the "Erase disk" option
# Set to false if you want to force manual partitioning
userSwapChoices:
  - none
  - reuse
  - small
  - suspend
  - file

# Minimum root partition size in GiB
requiredStorage: 10

# Allow zram instead of a swap partition
ensureSuspendToDisk: false
