# modules/services-systemd.conf
# Systemd services to enable/disable on the installed system.
---
services:
  - name: NetworkManager
    enabled: true
  - name: bluetooth
    enabled: true
  - name: cups
    enabled: false

targets:
  - name: graphical
    enabled: true
