# modules/users.conf
---
defaultGroups:
  - name: users
    must_exist: false
    system: false
  - name: lp
    must_exist: false
    system: false
  - name: video
    must_exist: false
    system: false
  - name: network
    must_exist: false
    system: false
  - name: storage
    must_exist: false
    system: false
  - name: wheel
    must_exist: false
    system: false
  - name: audio
    must_exist: false
    system: false
  - name: optical
    must_exist: false
    system: false

# Group that grants sudo access
sudoersGroup: wheel

# Auto-login for the created user
autologinGroup:  autologin
doAutologin:     false

# Set root password the same as user (not recommended for production)
setRootPassword: true

# Password requirements
passwordRequirements:
  minLength:        6
  maxLength:       -1
  libpwquality:
    - minlen=6

# Shell for the new user
userShell: /bin/bash
